### ISSUE TITLE
[🐈 Task]: Putting Log Files from Workflow Errors into Artifacts

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#559]
If the Actions fails: save the Log Files as artifacts so a contributor can export it. Explore ways to add a link to the artifact Log File so a contributor or maintainer can resolve the issue.

**Comment by miquelduranfrigola** [comment]
Hi,

There are several log files that are created at `fetch` time. At the moment, they are stored in temporary folders, which makes it difficult to trace them. I will collect these logs files in a pre-defined folder, so I hope it will be easier to gather the artifacts.

At `serve` time, I think there is only one log file, so it will be easy.

I have assigned this issue to myself. If I face problems with including artifacts, I will ask @megamanics or @honeyankit . Thanks!

**Comment by megamanics** [comment]
@miquelduranfrigola multiple paths with wildcards can be passed to collate the artifacts
```
      - name: Archive multiple artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fetch-logs
          path: |
            dist
            !dist/**/*.md
```
