### ISSUE TITLE
🐛 Bug:  Invalid YAML in workflows `install.yml`

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#791]
### Describe the bug.

The YAML check for `install.yml` in GitHub Actions workflows fails because this YAML is invalid. (Occurred here first: https://github.com/ersilia-os/ersilia/pull/790#issuecomment-1695375931)
This is because the `steps` key is duplicated within `jobs.base`. As per my understanding, probably the idea here is to test ersilia installation sans bentoml. One possible solution to fix this workflow is to create two separate jobs, one for installing ersilia with bentoml, the other for installing it without bentoml. Something like:

```YAML
jobs:
  with_bentoml:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Ersilia
      run: |
        python -m pip install git+https://github.com/ersilia-os/bentoml-ersilia.git
        python -m pip install -e .
    - name: Test help command
      run: |
        ersilia --help
        ersilia --version
  without_bentoml:
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Ersilia without pre-installing BentoML
      run: |
        python -m pip install -e .
    - name: Test help command again
      run: |
        ersilia --help
        ersilia --version
    - name: Fetch molecular weight model from DockerHub
      run: |
        ersilia -v fetch molecular-weight --from_dockerhub
```

### Operating environment

NA
